name: "Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Compile artefacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          extra-substituters = https://hydra.iohk.io
    - uses: cachix/cachix-action@v9
      with:
        name: shiba
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Format
      run: make format
    - name: Lint
      run: make hlint
    - name: Compile library
      run: make library
    - name: Run integration tests
      run: make test && ./result/
    - name: Compile executable
      run: make executable
    - name: Build Lambda
      run: make lambda